version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Starting the install phase..."
      - npm ci
      - echo "Dependencies installed successfully."

  pre_build:
    commands:
      - echo "Starting the test phase..."
      - CI=true npm test  # Ensures tests exit after completion
      - echo "Tests passed successfully."

  build:
    commands:
      - echo "Starting the build phase..."
      - npm run build
      - echo "Build completed successfully."

  post_build:
    commands:
      - echo "Starting deployment to S3..."
      - aws s3 sync build/ s3://$S3_BUCKET/ --delete
      - echo "Deployment to S3 completed."

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
